main:
  - name:  
    url: '#'
    weight: 10

  # - name: Home
  #   url: '#about'
  #   weight: 10
  # # - name: Posts
  # #   url: '#posts'
  # #   weight: 20
  # # - name: Projects
  # #   url: '#projects'
  # #   weight: 30
  # - name: Publications
  #   url: '#publications'
  #   weight: 40
  # - name: Seminars &nbsp &nbsp Conferences
  #   url: '#featured'
  #   weight: 50
  # - name: Contact
  #   url: '#contact'
  #   weight: 60
